// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeasonsCare.Api.Data;

#nullable disable

namespace SeasonsCare.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260416011326_AddResultJsonToAiHealthInsight")]
    partial class AddResultJsonToAiHealthInsight
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.AiHealthInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_from");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_to");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("KeyInsights")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_insights");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<string>("OverallSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("overall_summary");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recommendations");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("report_type");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text")
                        .HasColumnName("result_json");

                    b.Property<string>("SourceDataHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_data_hash");

                    b.Property<string>("TodaySummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("today_summary");

                    b.Property<string>("TrendLabels")
                        .HasColumnType("text")
                        .HasColumnName("trend_labels");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ai_health_insights");

                    b.HasIndex("CareGroupId", "ReportType", "DateFrom", "DateTo")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_health_insights_care_group_id_report_type_date_from_date");

                    b.ToTable("ai_health_insights", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.CareGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("HealthStatus")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("health_status");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invite_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("RecipientBirthDate")
                        .HasColumnType("date")
                        .HasColumnName("recipient_birth_date");

                    b.Property<string>("RecipientGender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recipient_gender");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recipient_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_care_groups");

                    b.ToTable("care_groups", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.CareGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_care_group_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_care_group_members_user_id");

                    b.HasIndex("CareGroupId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_care_group_members_care_group_id_user_id");

                    b.ToTable("care_group_members", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.CareLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<bool>("IsImportant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_important");

                    b.Property<string[]>("Participants")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("participants");

                    b.Property<string>("RepeatPattern")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("repeat_pattern");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("record_date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("log_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_care_logs");

                    b.HasIndex("CareGroupId")
                        .HasDatabaseName("ix_care_logs_care_group_id");

                    b.ToTable("care_logs", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.EventOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EventSeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_series_id");

                    b.Property<bool>("IsImportantOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("is_important_override");

                    b.Property<string>("OverrideDescription")
                        .HasColumnType("text")
                        .HasColumnName("override_description");

                    b.Property<string[]>("OverrideParticipants")
                        .HasColumnType("text[]")
                        .HasColumnName("override_participants");

                    b.Property<string>("OverrideTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("override_title");

                    b.Property<DateTime?>("ScheduledEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_end_at");

                    b.Property<DateTime>("ScheduledStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_event_occurrences");

                    b.HasIndex("CareGroupId")
                        .HasDatabaseName("ix_event_occurrences_care_group_id");

                    b.HasIndex("EventSeriesId", "ScheduledStartAt")
                        .IsUnique()
                        .HasDatabaseName("ix_event_occurrences_event_series_id_scheduled_start_at");

                    b.ToTable("event_occurrences", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.EventSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int?>("DaysOfWeekMask")
                        .HasColumnType("integer")
                        .HasColumnName("days_of_week_mask");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<int>("EndType")
                        .HasColumnType("integer")
                        .HasColumnName("end_type");

                    b.Property<bool>("IsImportant")
                        .HasColumnType("boolean")
                        .HasColumnName("is_important");

                    b.Property<int?>("OccurrenceCount")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_count");

                    b.Property<string[]>("Participants")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("participants");

                    b.Property<int>("RepeatInterval")
                        .HasColumnType("integer")
                        .HasColumnName("repeat_interval");

                    b.Property<int>("RepeatPattern")
                        .HasColumnType("integer")
                        .HasColumnName("repeat_pattern");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_event_series");

                    b.HasIndex("CareGroupId")
                        .HasDatabaseName("ix_event_series_care_group_id");

                    b.ToTable("event_series", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.ExpenseRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expense_date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("SplitStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("split_status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_expenses");

                    b.HasIndex("CareGroupId")
                        .HasDatabaseName("ix_expenses_care_group_id");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.BloodOxygenRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("record_date");

                    b.Property<decimal>("SpO2")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("sp_o2");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_blood_oxygens");

                    b.HasIndex("CareGroupId")
                        .HasDatabaseName("ix_blood_oxygens_care_group_id");

                    b.ToTable("blood_oxygens", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.BloodPressureRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Diastolic")
                        .HasColumnType("integer")
                        .HasColumnName("diastolic");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("record_date");

                    b.Property<int>("Systolic")
                        .HasColumnType("integer")
                        .HasColumnName("systolic");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_blood_pressures");

                    b.HasIndex("CareGroupId")
                        .HasDatabaseName("ix_blood_pressures_care_group_id");

                    b.ToTable("blood_pressures", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.BloodSugarRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("GlucoseLevel")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("glucose_level");

                    b.Property<string>("MeasurementContext")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("measurement_context");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("record_date");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_blood_sugars");

                    b.HasIndex("CareGroupId")
                        .HasDatabaseName("ix_blood_sugars_care_group_id");

                    b.ToTable("blood_sugars", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.TemperatureRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("record_date");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_temperatures");

                    b.HasIndex("CareGroupId")
                        .HasDatabaseName("ix_temperatures_care_group_id");

                    b.ToTable("temperatures", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.WeightRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("record_date");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_weights");

                    b.HasIndex("CareGroupId")
                        .HasDatabaseName("ix_weights_care_group_id");

                    b.ToTable("weights", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("avatar_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<Guid?>("LastViewedCareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_viewed_care_group_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("LastViewedCareGroupId")
                        .HasDatabaseName("ix_users_last_viewed_care_group_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.AiHealthInsight", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", "CareGroup")
                        .WithMany()
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ai_health_insights_care_groups_care_group_id");

                    b.Navigation("CareGroup");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.CareGroupMember", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", "CareGroup")
                        .WithMany("Members")
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_care_group_members_care_groups_care_group_id");

                    b.HasOne("SeasonsCare.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_care_group_members_users_user_id");

                    b.Navigation("CareGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.CareLog", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", "CareGroup")
                        .WithMany()
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_care_logs_care_groups_care_group_id");

                    b.Navigation("CareGroup");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.EventOccurrence", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", "CareGroup")
                        .WithMany()
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_occurrences_care_groups_care_group_id");

                    b.HasOne("SeasonsCare.Api.Models.Entities.EventSeries", "EventSeries")
                        .WithMany("Occurrences")
                        .HasForeignKey("EventSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_occurrences_event_series_event_series_id");

                    b.Navigation("CareGroup");

                    b.Navigation("EventSeries");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.EventSeries", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", "CareGroup")
                        .WithMany()
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_series_care_groups_care_group_id");

                    b.Navigation("CareGroup");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.ExpenseRecord", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", "CareGroup")
                        .WithMany()
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_care_groups_care_group_id");

                    b.Navigation("CareGroup");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.BloodOxygenRecord", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", "CareGroup")
                        .WithMany()
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_blood_oxygens_care_groups_care_group_id");

                    b.Navigation("CareGroup");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.BloodPressureRecord", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", "CareGroup")
                        .WithMany()
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_blood_pressures_care_groups_care_group_id");

                    b.Navigation("CareGroup");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.BloodSugarRecord", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", "CareGroup")
                        .WithMany()
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_blood_sugars_care_groups_care_group_id");

                    b.Navigation("CareGroup");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.TemperatureRecord", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", "CareGroup")
                        .WithMany()
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_temperatures_care_groups_care_group_id");

                    b.Navigation("CareGroup");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.WeightRecord", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", "CareGroup")
                        .WithMany()
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_weights_care_groups_care_group_id");

                    b.Navigation("CareGroup");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.User", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", null)
                        .WithMany()
                        .HasForeignKey("LastViewedCareGroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_care_groups_last_viewed_care_group_id");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.CareGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.EventSeries", b =>
                {
                    b.Navigation("Occurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
