// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeasonsCare.Api.Data;

#nullable disable

namespace SeasonsCare.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260324092012_AddBloodOxygenRecord")]
    partial class AddBloodOxygenRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.CareGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("HealthStatus")
                        .HasColumnType("text")
                        .HasColumnName("health_status");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invite_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_care_groups");

                    b.ToTable("care_groups", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.CareGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_care_group_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_care_group_members_user_id");

                    b.HasIndex("CareGroupId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_care_group_members_care_group_id_user_id");

                    b.ToTable("care_group_members", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.CareLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("LogType")
                        .HasColumnType("text")
                        .HasColumnName("log_type");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("record_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_care_logs");

                    b.HasIndex("CareGroupId")
                        .HasDatabaseName("ix_care_logs_care_group_id");

                    b.ToTable("care_logs", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.ExpenseRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expense_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_expenses");

                    b.HasIndex("CareGroupId")
                        .HasDatabaseName("ix_expenses_care_group_id");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.BloodOxygenRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("record_date");

                    b.Property<decimal>("SpO2")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("sp_o2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_blood_oxygens");

                    b.HasIndex("CareGroupId")
                        .HasDatabaseName("ix_blood_oxygens_care_group_id");

                    b.ToTable("blood_oxygens", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.BloodPressureRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Diastolic")
                        .HasColumnType("integer")
                        .HasColumnName("diastolic");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("record_date");

                    b.Property<int>("Systolic")
                        .HasColumnType("integer")
                        .HasColumnName("systolic");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_blood_pressures");

                    b.HasIndex("CareGroupId")
                        .HasDatabaseName("ix_blood_pressures_care_group_id");

                    b.ToTable("blood_pressures", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.BloodSugarRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("GlucoseLevel")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("glucose_level");

                    b.Property<string>("MeasurementContext")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("measurement_context");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("record_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_blood_sugars");

                    b.HasIndex("CareGroupId")
                        .HasDatabaseName("ix_blood_sugars_care_group_id");

                    b.ToTable("blood_sugars", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.TemperatureRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("record_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_temperatures");

                    b.HasIndex("CareGroupId")
                        .HasDatabaseName("ix_temperatures_care_group_id");

                    b.ToTable("temperatures", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.WeightRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CareGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("record_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_weights");

                    b.HasIndex("CareGroupId")
                        .HasDatabaseName("ix_weights_care_group_id");

                    b.ToTable("weights", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.CareGroupMember", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", "CareGroup")
                        .WithMany("Members")
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_care_group_members_care_groups_care_group_id");

                    b.HasOne("SeasonsCare.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_care_group_members_users_user_id");

                    b.Navigation("CareGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.CareLog", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", "CareGroup")
                        .WithMany()
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_care_logs_care_groups_care_group_id");

                    b.Navigation("CareGroup");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.ExpenseRecord", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", "CareGroup")
                        .WithMany()
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_care_groups_care_group_id");

                    b.Navigation("CareGroup");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.BloodOxygenRecord", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", "CareGroup")
                        .WithMany()
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_blood_oxygens_care_groups_care_group_id");

                    b.Navigation("CareGroup");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.BloodPressureRecord", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", "CareGroup")
                        .WithMany()
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_blood_pressures_care_groups_care_group_id");

                    b.Navigation("CareGroup");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.BloodSugarRecord", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", "CareGroup")
                        .WithMany()
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_blood_sugars_care_groups_care_group_id");

                    b.Navigation("CareGroup");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.TemperatureRecord", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", "CareGroup")
                        .WithMany()
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_temperatures_care_groups_care_group_id");

                    b.Navigation("CareGroup");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.HealthRecords.WeightRecord", b =>
                {
                    b.HasOne("SeasonsCare.Api.Models.Entities.CareGroup", "CareGroup")
                        .WithMany()
                        .HasForeignKey("CareGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_weights_care_groups_care_group_id");

                    b.Navigation("CareGroup");
                });

            modelBuilder.Entity("SeasonsCare.Api.Models.Entities.CareGroup", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
